# -*- coding: utf-8 -*-
"""placement_web.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lX7r9ELpRVkujqrwTX4pWHuyM2rKzUpC

# Importing the libraries
"""

import pandas as pd
import pickle
import warnings
warnings.filterwarnings('ignore')

"""## Importing the relevant excel file 'DataPlacement.xlsx'"""

df = pd.read_excel("DataPlacement.xlsx")
df.head()

"""## Changing the column headings to appropriate ones"""

df.columns = df.iloc[0]
df = df.iloc[1:]
df.head()

"""## 1) Changing the placement status as Placed: 1 and  NaN: 0
## 2) Dropping the categorical columns, Branch and Degree
"""

df.fillna(0,inplace=True)
df.replace('Placed',1,inplace=True)
df.drop(columns=['Branch','Degree'],inplace=True)

X=df.iloc[:,:-1]
y=df.iloc[:,-1]
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()
logreg.fit(X,y)
file = open('model.pkl', 'wb')
pickle.dump(logreg, file)
